<?php
session_start();
 if(isset($_SESSION['logout'])){
    unset($_SESSION['logout']);
    unset($_SESSION['username']);
    header("location:index.php");
  }else{
    header("location:login.php");
  }